name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: Swatinem/rust-cache@v2
      - run: go build
      - run: cargo build

  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: "nixpkgs=channel:release-23.11"
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build
